# Generated by Django 2.2.17 on 2021-01-16 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imggal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtitle', models.CharField(max_length=100)),
                ('imgdesc', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='scrap/media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=200)),
                ('test_content', models.TextField()),
                ('test_published', models.DateTimeField(default=datetime.datetime(2021, 1, 16, 1, 7, 9, 842776), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('item_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scrap.ItemCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200)),
                ('item_content', models.TextField()),
                ('item_published', models.DateTimeField(default=datetime.datetime(2021, 1, 16, 1, 7, 9, 844533), verbose_name='date published')),
                ('item_slug', models.CharField(default=1, max_length=200)),
                ('item_photo', models.ImageField(default=1, upload_to='photos/', verbose_name='Minha foto')),
                ('item_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scrap.ItemSeries', verbose_name='Series')),
            ],
        ),
    ]
