# Generated by Django 2.2.17 on 2021-01-17 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_auto_20210116_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_video',
            field=models.FileField(blank=True, default='def_vid.mp4', upload_to='videos', verbose_name='Custom video'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='photos/', verbose_name='Minha foto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 20, 14, 0, 680654), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 20, 14, 0, 679364), verbose_name='date published'),
        ),
    ]
