# Generated by Django 2.2.17 on 2021-01-17 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_auto_20210117_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 20, 31, 2, 156386), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_video',
            field=models.FileField(blank=True, default='def_vid.mp4', upload_to='videos/', verbose_name='Custom video'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 20, 31, 2, 154013), verbose_name='date published'),
        ),
    ]
