# Generated by Django 2.2.17 on 2021-03-24 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_auto_20210126_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 21, 13, 17, 250718), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 21, 13, 17, 249020), verbose_name='date published'),
        ),
    ]
