# Generated by Django 2.2.17 on 2021-07-07 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0008_auto_20210324_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 20, 5, 431554), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 16, 20, 5, 429163), verbose_name='date published'),
        ),
    ]
