# Generated by Django 2.2.17 on 2021-07-07 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_auto_20210707_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nick', models.CharField(max_length=200)),
                ('user_fname', models.CharField(max_length=200)),
                ('user_lname', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_dob', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 17, 8, 59, 150748), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 17, 8, 59, 149306), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_title', models.CharField(max_length=200)),
                ('comment_content', models.TextField()),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2021, 7, 7, 17, 8, 59, 152006), verbose_name='comment date')),
                ('comment_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scrap.ChatUser', verbose_name='users')),
                ('comment_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='scrap.Item', verbose_name='Items')),
            ],
        ),
    ]
