# Generated by Django 2.2.17 on 2021-07-09 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0022_auto_20210709_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatuser',
            options={'verbose_name_plural': 'ChatUsers'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 19, 30, 24, 658952), verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 19, 30, 24, 657676), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 19, 30, 24, 656193), verbose_name='date published'),
        ),
    ]
