# Generated by Django 2.2.17 on 2021-07-15 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0037_auto_20210715_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 20, 36, 31, 177645), verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_item',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 20, 36, 31, 176250), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 20, 36, 31, 174821), verbose_name='date published'),
        ),
    ]
