# Generated by Django 2.2.17 on 2021-07-16 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0039_auto_20210716_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(default='immo', on_delete=django.db.models.deletion.SET_DEFAULT, to='scrap.ChatUser', verbose_name='ChatUsers'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 16, 15, 47, 868026), verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 16, 15, 47, 866655), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 16, 15, 47, 865223), verbose_name='date published'),
        ),
    ]
