# Generated by Django 2.2.17 on 2021-07-16 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0040_auto_20210716_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 16, 17, 56, 53195), verbose_name='comment date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_item',
            field=models.ForeignKey(default='Teste', on_delete=django.db.models.deletion.SET_DEFAULT, to='scrap.Item', verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 16, 17, 56, 51784), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 16, 17, 56, 50369), verbose_name='date published'),
        ),
    ]
